FROM ez_php:latest

# Install Node.js and Yarn
RUN apt-get update -q -y \
    && apt-get install -q -y --no-install-recommends gnupg \ 
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs \
    && curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && sudo apt-get update && sudo apt-get install yarn \
    && rm -rf /var/lib/apt/lists/*
