FROM ez_php

# Add additional packages for dev use
RUN apt-get update -q -y \
 && apt-get install -q -y --no-install-recommends \
        less \
        mariadb-client \
        vim \
        wget \
        tree \
        gdb-minimal \
        && rm -rf /var/lib/apt/lists/*

# Install xdebug
RUN echo yes | pecl install -o xdebug
COPY conf.d/xdebug.ini ${PHP_INI_DIR}/conf.d/xdebug.ini
