
name: Build and test Docker images
on:
    push:
        branches:
            - master
            - "[0-9]+.[0-9]+"
    pull_request: ~

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php:
                    - "7.3"
                    - "7.4"
                    - "8.0"
                    - "8.1"
                    - "8.2"
                node:
                    # - "12"
                    - "14"

        steps:
            - uses: actions/checkout@v2
            - name: Set Docker version
              run: bin/.travis/update_docker.sh
            - name: Build image
              run: bin/.travis/build.sh ${{ matrix.php }} ${{ matrix.node }}
            - name: Test image
              run: bin/.travis/test.sh
              env:
                TEST_CMD: "vendor/bin/behat -v --profile=browser --suite=admin-ui --tags=@richtext --config=behat_ibexa_oss.yaml"
            - name: Push image
              if: github.ref_name == 'master' || github.ref_name == 'v1'
              run: bin/.travis/push.sh ezsystems/php v2
